### ISSUE TITLE
Service Battery Warning

### ISSUE THREAD

**Issue by W-MS** [jardenliu/XPS15-9560-Catalina-Preview#3]
<img width="237" alt="截屏2019-10-02下午1 13 26" src="https://user-images.githubusercontent.com/4151402/66019575-a6ae6900-e516-11e9-996a-37e50a527b7c.png">
Here is the warning. Maybe because I'm using a 97 Wh batt instead of a 54 Wh one.
Maybe I can replace something in config.plist or how can I fix it?

Thanks

**Comment by LeLunZ** [comment]
Are you sure its because of 97 Wh Battery. 
Check your battery level in System monitor/ System information.

![Bildschirmfoto 2019-10-07 um 21 14 51](https://user-images.githubusercontent.com/31982496/66341460-a283b080-e947-11e9-8da3-135194614667.png)

check Volle Ladekapazität (in mAh):/ Full capacity (in mAH)

report back

**Comment by W-MS** [comment]
<img width="607" alt="Screen Shot 2019-10-08 at 6 22 01 PM" src="https://user-images.githubusercontent.com/4151402/66388375-8c81f880-e9f8-11e9-8f3e-d8de1539e2ff.png">

**Comment by LeLunZ** [comment]
Seems like your battery is also slowly dying. It has like 79 percent of its original power at full capacity.

How old is the battery? Two years or more?
